[project]
name = "cuplyk"
version = "0.1.0"
description = "cuplyk"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
    "django-tailwind[cookiecutter,honcho,reload]>=4.4.2",
]
